// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebSocket.Shared.DataAcess.Local;

#nullable disable

namespace WebSocket.Shared.Migrations
{
    [DbContext(typeof(SalkySqlLiteDbContext))]
    [Migration("20220404142129_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("WebSocket.Shared.DataAcess.Models.Contato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExibitionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NickColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PictureSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Contatos");
                });

            modelBuilder.Entity("WebSocket.Shared.DataAcess.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContatoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSended")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContatoId");

                    b.ToTable("Mensagens");
                });

            modelBuilder.Entity("WebSocket.Shared.DataAcess.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExibitionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NickColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PictureSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PrivateKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<bool>("VisivelUltimoLogin")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("WebSocket.Shared.DataAcess.Models.Contato", b =>
                {
                    b.HasOne("WebSocket.Shared.DataAcess.Models.Usuario", null)
                        .WithMany("Contatos")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("WebSocket.Shared.DataAcess.Models.Message", b =>
                {
                    b.HasOne("WebSocket.Shared.DataAcess.Models.Contato", null)
                        .WithMany("Messages")
                        .HasForeignKey("ContatoId");
                });

            modelBuilder.Entity("WebSocket.Shared.DataAcess.Models.Contato", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("WebSocket.Shared.DataAcess.Models.Usuario", b =>
                {
                    b.Navigation("Contatos");
                });
#pragma warning restore 612, 618
        }
    }
}
